.TH LOCALEMBED-CLI 1 "2026-03-03" "v1.0.2" "MLC LocalEmbed"
.SH NAME
localembed-cli \- Client for LocalEmbed service
.SH SYNOPSIS
.B localembed-cli
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B localembed-cli
is a command-line tool to interact with the localembed-server.
.SH OPTIONS
.TP
.B -text "Hello"
The text to embed.
.SH SEE ALSO
.B localembed-server(1)
.SH AUTHOR
Michael Lechner
