name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Download ONNX Runtime
        shell: bash
        run: |
          URL="https://github.com/microsoft/onnxruntime/releases/download/v1.17.0/onnxruntime-linux-x64-1.17.0.tgz"
          LIB="libonnxruntime.so.1.17.0"
          curl -L $URL -o onnxruntime.tgz
          tar -xzf onnxruntime.tgz
          find . -name "$LIB" -exec cp {} . \;
          ln -sf $LIB libonnxruntime.so

      - name: Run Tests
        env:
          ONNX_PATH: ${{ github.workspace }}/libonnxruntime.so
          GOWORK: "off"
        run: go test -v ./...

      - name: Build Check
        env:
          GOWORK: "off"
        run: |
          mkdir -p bin
          go build -v -o bin/server ./cmd/server/main.go
          go build -v -o bin/preloader ./cmd/preloader/main.go
          go build -v -o bin/cli ./cmd/cli/main.go
